# Generated by Django 4.2.7 on 2025-05-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuildingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "building_type",
                    models.CharField(
                        choices=[
                            ("school", "Школа"),
                            ("hospital", "Больница"),
                            ("kindergarten", "Детский сад"),
                            ("pharmacy", "Аптека"),
                            ("shopping_center", "Торговый центр"),
                            ("park", "Парк"),
                        ],
                        max_length=50,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("suggested_lat", models.FloatField()),
                ("suggested_lng", models.FloatField()),
                ("population_density", models.FloatField()),
                ("confidence_score", models.FloatField()),
                ("reasoning", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PopulationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district_name", models.CharField(max_length=200)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("population_density", models.IntegerField()),
                ("city", models.CharField(max_length=100)),
            ],
        ),
    ]
